/*
 * PreferenceManager2.java
 *
 * Created on 15. Oktober 2006, 16:34
 */

package de.unisiegen.tpml.ui;

import java.awt.Font;

import org.apache.log4j.Logger;

import de.unisiegen.tpml.graphics.theme.ThemeManager;

/**
 * 
 * @author TPPool15
 */
public class PreferenceDialog extends javax.swing.JDialog {

	/** Creates new form PreferenceManager2 */
	public PreferenceDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		thememanager = ThemeManager.get();
		int length = thememanager.getNumberOfThemes();
		for (int i = 0; i < length; i++) {
			themeBox.addItem(thememanager.getTheme(i).getName());
		}
		String[] itemnames = thememanager.getTheme(themeBox.getSelectedIndex())
				.getItemNames();

		itemList.setListData(itemnames);
		
		itemList.setSelectedIndex(0);
		colorPanel.setBackground(thememanager.getCurrentTheme().getItemColor(0));
		Font itemfont = thememanager.getCurrentTheme().getItemFont(0);
		if (itemfont != null){
			fontButton.setEnabled(true);
			fontLabel.setText("Font is: "+ itemfont.getFontName());
		}
		else {
			fontButton.setEnabled(false);
			fontLabel.setText("");
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JPanel buttonPanel;
        javax.swing.JPanel centerPanel;
        javax.swing.JLabel chooseLabel;
        javax.swing.JButton closeButton;
        javax.swing.JButton deleteButton;
        javax.swing.JPanel eastPanel;
        javax.swing.JPanel fontPanel;
        javax.swing.JScrollPane itemScrollPane;
        javax.swing.JButton newButton;
        javax.swing.JPanel northPanel;
        javax.swing.JPanel southPanel;
        javax.swing.JPanel westPanel;

        northPanel = new javax.swing.JPanel();
        chooseLabel = new javax.swing.JLabel();
        themeBox = new javax.swing.JComboBox();
        buttonPanel = new javax.swing.JPanel();
        newButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        westPanel = new javax.swing.JPanel();
        colorBotton = new javax.swing.JButton();
        fontButton = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        colorPanel = new javax.swing.JPanel();
        fontPanel = new javax.swing.JPanel();
        fontLabel = new javax.swing.JLabel();
        eastPanel = new javax.swing.JPanel();
        itemScrollPane = new javax.swing.JScrollPane();
        itemList = new javax.swing.JList();
        southPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preferences");
        northPanel.setLayout(new java.awt.BorderLayout());

        chooseLabel.setText("Choose Theme:");
        chooseLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        northPanel.add(chooseLabel, java.awt.BorderLayout.NORTH);

        themeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeBoxActionPerformed(evt);
            }
        });

        northPanel.add(themeBox, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 5));

        newButton.setText("New");
        buttonPanel.add(newButton);

        deleteButton.setText("Delete");
        buttonPanel.add(deleteButton);

        northPanel.add(buttonPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(northPanel, java.awt.BorderLayout.NORTH);

        westPanel.setLayout(new javax.swing.BoxLayout(westPanel, javax.swing.BoxLayout.Y_AXIS));

        colorBotton.setText("Color");
        westPanel.add(colorBotton);

        fontButton.setText("Font");
        westPanel.add(fontButton);

        getContentPane().add(westPanel, java.awt.BorderLayout.WEST);

        centerPanel.setLayout(new javax.swing.BoxLayout(centerPanel, javax.swing.BoxLayout.Y_AXIS));

        colorPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        colorPanel.setBackground(new java.awt.Color(0, 0, 204));
        colorPanel.setMaximumSize(new java.awt.Dimension(32767, 23));
        colorPanel.setMinimumSize(new java.awt.Dimension(10, 23));
        colorPanel.setPreferredSize(new java.awt.Dimension(100, 23));
        centerPanel.add(colorPanel);

        fontPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        fontPanel.setMaximumSize(new java.awt.Dimension(32767, 23));
        fontPanel.setMinimumSize(new java.awt.Dimension(10, 23));
        fontPanel.setPreferredSize(new java.awt.Dimension(100, 23));
        fontLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fontLabel.setText("This is Thahoma");
        fontPanel.add(fontLabel);

        centerPanel.add(fontPanel);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        eastPanel.setLayout(new javax.swing.BoxLayout(eastPanel, javax.swing.BoxLayout.X_AXIS));

        itemList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "A really looong name" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        itemList.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                itemListPropertyChange(evt);
            }
        });
        itemList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                itemListValueChanged(evt);
            }
        });

        itemScrollPane.setViewportView(itemList);

        eastPanel.add(itemScrollPane);

        getContentPane().add(eastPanel, java.awt.BorderLayout.EAST);

        southPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 5));

        closeButton.setText("Close");
        southPanel.add(closeButton);

        getContentPane().add(southPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_itemListValueChanged
// TODO add your handling code here:
        logger.debug("Selected Item is: "+itemList.getSelectedValue());
        colorPanel.setBackground(thememanager.getCurrentTheme().getItemColor(itemList.getSelectedIndex()));
		Font itemfont = thememanager.getCurrentTheme().getItemFont(itemList.getSelectedIndex());
		if (itemfont != null){
			fontButton.setEnabled(true);
			fontLabel.setText(""+ itemfont.getFontName());
		}
		else {
			fontButton.setEnabled(false);
			fontLabel.setText("");
		}
    }//GEN-LAST:event_itemListValueChanged

        private void itemListPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_itemListPropertyChange
// TODO add your handling code here:
        }//GEN-LAST:event_itemListPropertyChange

	private void themeBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_themeBoxActionPerformed
	// TODO add your handling code here:
		thememanager.setCurrentThem(thememanager.getTheme(themeBox
				.getSelectedIndex()));
		logger.debug("Set the current theme to: "
				+ thememanager.getCurrentTheme().getName());
	}// GEN-LAST:event_themeBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colorBotton;
    private javax.swing.JPanel colorPanel;
    private javax.swing.JButton fontButton;
    private javax.swing.JLabel fontLabel;
    private javax.swing.JList itemList;
    private javax.swing.JComboBox themeBox;
    // End of variables declaration//GEN-END:variables

	private ThemeManager thememanager;

	private static Logger logger = Logger.getLogger(PreferenceDialog.class);
}
