/* This file was generated by SableCC (http://www.sablecc.org/). */

package l1.parser;

import l1.lexer.*;
import l1.node.*;
import l1.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;
    }

    private void push(int numstate, ArrayList listNode) throws ParserException, LexerException, IOException
    {
	this.nodeList = listNode;

        if(!stack.hasNext())
        {
            stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) stack.previous();
        stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return (ArrayList) ((State) stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        converter.index = -1;
        token.apply(converter);
        return converter.index;
    }

    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);
        List ign = null;
        while(true)
        {
            while(index(lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedLinkedList(NodeCast.instance);
                }

                ign.add(lexer.next());
            }

            if(ign != null)
            {
                ignoredTokens.setIn(lexer.peek(), ign);
                ign = null;
            }

            last_pos = lexer.peek().getPos();
            last_line = lexer.peek().getLine();
            last_token = lexer.peek();

            int index = index(lexer.peek());
            action[0] = actionTable[state()][0][1];
            action[1] = actionTable[state()][0][2];

            int low = 1;
            int high = actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[state()][middle][1];
                    action[1] = actionTable[state()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(lexer.next());
                        push(action[1], list);
                        last_shift = action[1];
                    }
		    break;
                case REDUCE:
                    switch(action[1])
                    {
                    case 0: /* reduce AConjunctionExpression */
		    {
			ArrayList list = new0();
			push(goTo(0), list);
		    }
		    break;
                    case 1: /* reduce AConditionExpression */
		    {
			ArrayList list = new1();
			push(goTo(0), list);
		    }
		    break;
                    case 2: /* reduce ALetExpression */
		    {
			ArrayList list = new2();
			push(goTo(0), list);
		    }
		    break;
                    case 3: /* reduce ALetrecExpression */
		    {
			ArrayList list = new3();
			push(goTo(0), list);
		    }
		    break;
                    case 4: /* reduce AAbstractionExpression */
		    {
			ArrayList list = new4();
			push(goTo(0), list);
		    }
		    break;
                    case 5: /* reduce ARecursionExpression */
		    {
			ArrayList list = new5();
			push(goTo(0), list);
		    }
		    break;
                    case 6: /* reduce AComparisonConjunction */
		    {
			ArrayList list = new6();
			push(goTo(1), list);
		    }
		    break;
                    case 7: /* reduce AOrConjunction */
		    {
			ArrayList list = new7();
			push(goTo(1), list);
		    }
		    break;
                    case 8: /* reduce AAndConjunction */
		    {
			ArrayList list = new8();
			push(goTo(1), list);
		    }
		    break;
                    case 9: /* reduce ATermComparison */
		    {
			ArrayList list = new9();
			push(goTo(2), list);
		    }
		    break;
                    case 10: /* reduce ALowerThanComparison */
		    {
			ArrayList list = new10();
			push(goTo(2), list);
		    }
		    break;
                    case 11: /* reduce AGreaterThanComparison */
		    {
			ArrayList list = new11();
			push(goTo(2), list);
		    }
		    break;
                    case 12: /* reduce ALowerEqualComparison */
		    {
			ArrayList list = new12();
			push(goTo(2), list);
		    }
		    break;
                    case 13: /* reduce AGreaterEqualComparison */
		    {
			ArrayList list = new13();
			push(goTo(2), list);
		    }
		    break;
                    case 14: /* reduce AEqualComparison */
		    {
			ArrayList list = new14();
			push(goTo(2), list);
		    }
		    break;
                    case 15: /* reduce AFactorTerm */
		    {
			ArrayList list = new15();
			push(goTo(3), list);
		    }
		    break;
                    case 16: /* reduce AAdditionTerm */
		    {
			ArrayList list = new16();
			push(goTo(3), list);
		    }
		    break;
                    case 17: /* reduce ASubstractionTerm */
		    {
			ArrayList list = new17();
			push(goTo(3), list);
		    }
		    break;
                    case 18: /* reduce AApplicationFactor */
		    {
			ArrayList list = new18();
			push(goTo(4), list);
		    }
		    break;
                    case 19: /* reduce AMultiplicationFactor */
		    {
			ArrayList list = new19();
			push(goTo(4), list);
		    }
		    break;
                    case 20: /* reduce ADivisionFactor */
		    {
			ArrayList list = new20();
			push(goTo(4), list);
		    }
		    break;
                    case 21: /* reduce AModulationFactor */
		    {
			ArrayList list = new21();
			push(goTo(4), list);
		    }
		    break;
                    case 22: /* reduce AAtomApplication */
		    {
			ArrayList list = new22();
			push(goTo(5), list);
		    }
		    break;
                    case 23: /* reduce AApplicationApplication */
		    {
			ArrayList list = new23();
			push(goTo(5), list);
		    }
		    break;
                    case 24: /* reduce AConstantAtom */
		    {
			ArrayList list = new24();
			push(goTo(6), list);
		    }
		    break;
                    case 25: /* reduce AIdentifierAtom */
		    {
			ArrayList list = new25();
			push(goTo(6), list);
		    }
		    break;
                    case 26: /* reduce AExpressionAtom */
		    {
			ArrayList list = new26();
			push(goTo(6), list);
		    }
		    break;
                    case 27: /* reduce AUnitConstant */
		    {
			ArrayList list = new27();
			push(goTo(7), list);
		    }
		    break;
                    case 28: /* reduce ABoolConstant */
		    {
			ArrayList list = new28();
			push(goTo(7), list);
		    }
		    break;
                    case 29: /* reduce ANumberConstant */
		    {
			ArrayList list = new29();
			push(goTo(7), list);
		    }
		    break;
                    case 30: /* reduce AOperatorConstant */
		    {
			ArrayList list = new30();
			push(goTo(7), list);
		    }
		    break;
                    case 31: /* reduce ATrueBool */
		    {
			ArrayList list = new31();
			push(goTo(8), list);
		    }
		    break;
                    case 32: /* reduce AFalseBool */
		    {
			ArrayList list = new32();
			push(goTo(8), list);
		    }
		    break;
                    case 33: /* reduce APlusOperator */
		    {
			ArrayList list = new33();
			push(goTo(9), list);
		    }
		    break;
                    case 34: /* reduce AMinusOperator */
		    {
			ArrayList list = new34();
			push(goTo(9), list);
		    }
		    break;
                    case 35: /* reduce AMultiplyOperator */
		    {
			ArrayList list = new35();
			push(goTo(9), list);
		    }
		    break;
                    case 36: /* reduce ADivideOperator */
		    {
			ArrayList list = new36();
			push(goTo(9), list);
		    }
		    break;
                    case 37: /* reduce AModuloOperator */
		    {
			ArrayList list = new37();
			push(goTo(9), list);
		    }
		    break;
                    case 38: /* reduce ALowerThanOperator */
		    {
			ArrayList list = new38();
			push(goTo(9), list);
		    }
		    break;
                    case 39: /* reduce AGreaterThanOperator */
		    {
			ArrayList list = new39();
			push(goTo(9), list);
		    }
		    break;
                    case 40: /* reduce ALowerEqualOperator */
		    {
			ArrayList list = new40();
			push(goTo(9), list);
		    }
		    break;
                    case 41: /* reduce AGreaterEqualOperator */
		    {
			ArrayList list = new41();
			push(goTo(9), list);
		    }
		    break;
                    case 42: /* reduce AEqualOperator */
		    {
			ArrayList list = new42();
			push(goTo(9), list);
		    }
		    break;
                    case 43: /* reduce AAndOperator */
		    {
			ArrayList list = new43();
			push(goTo(9), list);
		    }
		    break;
                    case 44: /* reduce AOrOperator */
		    {
			ArrayList list = new44();
			push(goTo(9), list);
		    }
		    break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.next();
                        PExpression node1 = (PExpression) ((ArrayList)pop()).get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }



    ArrayList new0() /* reduce AConjunctionExpression */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new1() /* reduce AConditionExpression */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList6.get(0);

        pexpressionNode1 = new AConditionExpression(pexpressionNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new2() /* reduce ALetExpression */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TIdentifier tidentifierNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        tidentifierNode2 = (TIdentifier)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList6.get(0);

        pexpressionNode1 = new ALetExpression(tidentifierNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new3() /* reduce ALetrecExpression */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TIdentifier tidentifierNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList5.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList7.get(0);

        pexpressionNode1 = new ALetrecExpression(tidentifierNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new4() /* reduce AAbstractionExpression */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TIdentifier tidentifierNode2;
        PExpression pexpressionNode3;
        tidentifierNode2 = (TIdentifier)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pexpressionNode1 = new AAbstractionExpression(tidentifierNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new5() /* reduce ARecursionExpression */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TIdentifier tidentifierNode2;
        PExpression pexpressionNode3;
        tidentifierNode2 = (TIdentifier)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pexpressionNode1 = new ARecursionExpression(tidentifierNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new6() /* reduce AComparisonConjunction */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new7() /* reduce AOrConjunction */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode5;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TOr torNode4;
        torNode4 = (TOr)nodeArrayList2.get(0);

        pexpressionNode3 = new AOrExpression(torNode4);
        }
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AInfixExpression(pexpressionNode2, pexpressionNode3, pexpressionNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new8() /* reduce AAndConjunction */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode5;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TAnd tandNode4;
        tandNode4 = (TAnd)nodeArrayList2.get(0);

        pexpressionNode3 = new AAndExpression(tandNode4);
        }
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AInfixExpression(pexpressionNode2, pexpressionNode3, pexpressionNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new9() /* reduce ATermComparison */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new10() /* reduce ALowerThanComparison */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode5;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TLowerThan tlowerthanNode4;
        tlowerthanNode4 = (TLowerThan)nodeArrayList2.get(0);

        pexpressionNode3 = new ALowerThanExpression(tlowerthanNode4);
        }
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AInfixExpression(pexpressionNode2, pexpressionNode3, pexpressionNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new11() /* reduce AGreaterThanComparison */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode5;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TGreaterThan tgreaterthanNode4;
        tgreaterthanNode4 = (TGreaterThan)nodeArrayList2.get(0);

        pexpressionNode3 = new AGreaterThanExpression(tgreaterthanNode4);
        }
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AInfixExpression(pexpressionNode2, pexpressionNode3, pexpressionNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new12() /* reduce ALowerEqualComparison */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode5;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TLowerEqual tlowerequalNode4;
        tlowerequalNode4 = (TLowerEqual)nodeArrayList2.get(0);

        pexpressionNode3 = new ALowerEqualExpression(tlowerequalNode4);
        }
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AInfixExpression(pexpressionNode2, pexpressionNode3, pexpressionNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new13() /* reduce AGreaterEqualComparison */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode5;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TGreaterEqual tgreaterequalNode4;
        tgreaterequalNode4 = (TGreaterEqual)nodeArrayList2.get(0);

        pexpressionNode3 = new AGreaterEqualExpression(tgreaterequalNode4);
        }
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AInfixExpression(pexpressionNode2, pexpressionNode3, pexpressionNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new14() /* reduce AEqualComparison */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode5;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TEqual tequalNode4;
        tequalNode4 = (TEqual)nodeArrayList2.get(0);

        pexpressionNode3 = new AEqualExpression(tequalNode4);
        }
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AInfixExpression(pexpressionNode2, pexpressionNode3, pexpressionNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new15() /* reduce AFactorTerm */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new16() /* reduce AAdditionTerm */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode5;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TPlus tplusNode4;
        tplusNode4 = (TPlus)nodeArrayList2.get(0);

        pexpressionNode3 = new APlusExpression(tplusNode4);
        }
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AInfixExpression(pexpressionNode2, pexpressionNode3, pexpressionNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new17() /* reduce ASubstractionTerm */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode5;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TMinus tminusNode4;
        tminusNode4 = (TMinus)nodeArrayList2.get(0);

        pexpressionNode3 = new AMinusExpression(tminusNode4);
        }
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AInfixExpression(pexpressionNode2, pexpressionNode3, pexpressionNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new18() /* reduce AApplicationFactor */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new19() /* reduce AMultiplicationFactor */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode5;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TMultiply tmultiplyNode4;
        tmultiplyNode4 = (TMultiply)nodeArrayList2.get(0);

        pexpressionNode3 = new AMultiplyExpression(tmultiplyNode4);
        }
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AInfixExpression(pexpressionNode2, pexpressionNode3, pexpressionNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new20() /* reduce ADivisionFactor */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode5;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TDivide tdivideNode4;
        tdivideNode4 = (TDivide)nodeArrayList2.get(0);

        pexpressionNode3 = new ADivideExpression(tdivideNode4);
        }
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AInfixExpression(pexpressionNode2, pexpressionNode3, pexpressionNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new21() /* reduce AModulationFactor */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode5;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TModulo tmoduloNode4;
        tmoduloNode4 = (TModulo)nodeArrayList2.get(0);

        pexpressionNode3 = new AModuloExpression(tmoduloNode4);
        }
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AInfixExpression(pexpressionNode2, pexpressionNode3, pexpressionNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new22() /* reduce AAtomApplication */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new23() /* reduce AApplicationApplication */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList2.get(0);

        pexpressionNode1 = new AApplicationExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new24() /* reduce AConstantAtom */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new25() /* reduce AIdentifierAtom */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);

        pexpressionNode1 = new AIdentifierExpression(tidentifierNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new26() /* reduce AExpressionAtom */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList2.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new27() /* reduce AUnitConstant */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TUnit tunitNode2;
        tunitNode2 = (TUnit)nodeArrayList1.get(0);

        pexpressionNode1 = new AUnitExpression(tunitNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new28() /* reduce ABoolConstant */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new29() /* reduce ANumberConstant */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TNumber tnumberNode2;
        tnumberNode2 = (TNumber)nodeArrayList1.get(0);

        pexpressionNode1 = new ANumberExpression(tnumberNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new30() /* reduce AOperatorConstant */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList2.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new31() /* reduce ATrueBool */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TTrue ttrueNode2;
        ttrueNode2 = (TTrue)nodeArrayList1.get(0);

        pexpressionNode1 = new ATrueExpression(ttrueNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new32() /* reduce AFalseBool */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TFalse tfalseNode2;
        tfalseNode2 = (TFalse)nodeArrayList1.get(0);

        pexpressionNode1 = new AFalseExpression(tfalseNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new33() /* reduce APlusOperator */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TPlus tplusNode2;
        tplusNode2 = (TPlus)nodeArrayList1.get(0);

        pexpressionNode1 = new APlusExpression(tplusNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new34() /* reduce AMinusOperator */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TMinus tminusNode2;
        tminusNode2 = (TMinus)nodeArrayList1.get(0);

        pexpressionNode1 = new AMinusExpression(tminusNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new35() /* reduce AMultiplyOperator */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TMultiply tmultiplyNode2;
        tmultiplyNode2 = (TMultiply)nodeArrayList1.get(0);

        pexpressionNode1 = new AMultiplyExpression(tmultiplyNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new36() /* reduce ADivideOperator */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TDivide tdivideNode2;
        tdivideNode2 = (TDivide)nodeArrayList1.get(0);

        pexpressionNode1 = new ADivideExpression(tdivideNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new37() /* reduce AModuloOperator */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TModulo tmoduloNode2;
        tmoduloNode2 = (TModulo)nodeArrayList1.get(0);

        pexpressionNode1 = new AModuloExpression(tmoduloNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new38() /* reduce ALowerThanOperator */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TLowerThan tlowerthanNode2;
        tlowerthanNode2 = (TLowerThan)nodeArrayList1.get(0);

        pexpressionNode1 = new ALowerThanExpression(tlowerthanNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new39() /* reduce AGreaterThanOperator */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TGreaterThan tgreaterthanNode2;
        tgreaterthanNode2 = (TGreaterThan)nodeArrayList1.get(0);

        pexpressionNode1 = new AGreaterThanExpression(tgreaterthanNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new40() /* reduce ALowerEqualOperator */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TLowerEqual tlowerequalNode2;
        tlowerequalNode2 = (TLowerEqual)nodeArrayList1.get(0);

        pexpressionNode1 = new ALowerEqualExpression(tlowerequalNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new41() /* reduce AGreaterEqualOperator */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TGreaterEqual tgreaterequalNode2;
        tgreaterequalNode2 = (TGreaterEqual)nodeArrayList1.get(0);

        pexpressionNode1 = new AGreaterEqualExpression(tgreaterequalNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new42() /* reduce AEqualOperator */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TEqual tequalNode2;
        tequalNode2 = (TEqual)nodeArrayList1.get(0);

        pexpressionNode1 = new AEqualExpression(tequalNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new43() /* reduce AAndOperator */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TAnd tandNode2;
        tandNode2 = (TAnd)nodeArrayList1.get(0);

        pexpressionNode1 = new AAndExpression(tandNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new44() /* reduce AOrOperator */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TOr torNode2;
        torNode2 = (TOr)nodeArrayList1.get(0);

        pexpressionNode1 = new AOrExpression(torNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {10, SHIFT, 1}, {15, SHIFT, 2}, {18, SHIFT, 3}, {19, SHIFT, 4}, {21, SHIFT, 5}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 1}, {0, SHIFT, 20}, {1, SHIFT, 21}, {2, SHIFT, 22}, {3, SHIFT, 23}, {4, SHIFT, 24}, {5, SHIFT, 25}, {6, SHIFT, 26}, {7, SHIFT, 27}, {8, SHIFT, 28}, {9, SHIFT, 29}, {10, SHIFT, 1}, {13, SHIFT, 30}, {14, SHIFT, 31}, {15, SHIFT, 2}, {18, SHIFT, 3}, {19, SHIFT, 4}, {21, SHIFT, 5}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 2}, {10, SHIFT, 1}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 3}, {26, SHIFT, 35}, },
			{{-1, ERROR, 4}, {21, SHIFT, 36}, {26, SHIFT, 37}, },
			{{-1, ERROR, 5}, {26, SHIFT, 38}, },
			{{-1, REDUCE, 27}, },
			{{-1, REDUCE, 31}, },
			{{-1, REDUCE, 32}, },
			{{-1, REDUCE, 29}, },
			{{-1, REDUCE, 25}, },
			{{-1, ERROR, 11}, {27, ACCEPT, -1}, },
			{{-1, REDUCE, 0}, {13, SHIFT, 39}, {14, SHIFT, 40}, },
			{{-1, REDUCE, 6}, {5, SHIFT, 41}, {6, SHIFT, 42}, {7, SHIFT, 43}, {8, SHIFT, 44}, {9, SHIFT, 45}, },
			{{-1, REDUCE, 9}, {0, SHIFT, 46}, {1, SHIFT, 47}, },
			{{-1, REDUCE, 15}, {2, SHIFT, 48}, {3, SHIFT, 49}, {4, SHIFT, 50}, },
			{{-1, REDUCE, 18}, {10, SHIFT, 1}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, REDUCE, 22}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 28}, },
			{{-1, REDUCE, 33}, },
			{{-1, REDUCE, 34}, },
			{{-1, REDUCE, 35}, },
			{{-1, REDUCE, 36}, },
			{{-1, REDUCE, 37}, },
			{{-1, REDUCE, 38}, },
			{{-1, REDUCE, 39}, },
			{{-1, REDUCE, 40}, },
			{{-1, REDUCE, 41}, },
			{{-1, REDUCE, 42}, },
			{{-1, REDUCE, 43}, },
			{{-1, REDUCE, 44}, },
			{{-1, ERROR, 32}, {11, SHIFT, 52}, },
			{{-1, ERROR, 33}, {11, SHIFT, 53}, },
			{{-1, ERROR, 34}, {13, SHIFT, 39}, {14, SHIFT, 40}, {16, SHIFT, 54}, },
			{{-1, ERROR, 35}, {12, SHIFT, 55}, },
			{{-1, ERROR, 36}, {26, SHIFT, 56}, },
			{{-1, ERROR, 37}, {9, SHIFT, 57}, },
			{{-1, ERROR, 38}, {12, SHIFT, 58}, },
			{{-1, ERROR, 39}, {10, SHIFT, 1}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 40}, {10, SHIFT, 1}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 41}, {10, SHIFT, 1}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 42}, {10, SHIFT, 1}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 43}, {10, SHIFT, 1}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 44}, {10, SHIFT, 1}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 45}, {10, SHIFT, 1}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 46}, {10, SHIFT, 1}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 47}, {10, SHIFT, 1}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 48}, {10, SHIFT, 1}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 49}, {10, SHIFT, 1}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 50}, {10, SHIFT, 1}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, REDUCE, 23}, },
			{{-1, REDUCE, 26}, },
			{{-1, REDUCE, 30}, },
			{{-1, ERROR, 54}, {10, SHIFT, 1}, {15, SHIFT, 2}, {18, SHIFT, 3}, {19, SHIFT, 4}, {21, SHIFT, 5}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 55}, {10, SHIFT, 1}, {15, SHIFT, 2}, {18, SHIFT, 3}, {19, SHIFT, 4}, {21, SHIFT, 5}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 56}, {9, SHIFT, 73}, },
			{{-1, ERROR, 57}, {10, SHIFT, 1}, {15, SHIFT, 2}, {18, SHIFT, 3}, {19, SHIFT, 4}, {21, SHIFT, 5}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 58}, {10, SHIFT, 1}, {15, SHIFT, 2}, {18, SHIFT, 3}, {19, SHIFT, 4}, {21, SHIFT, 5}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, REDUCE, 8}, {5, SHIFT, 41}, {6, SHIFT, 42}, {7, SHIFT, 43}, {8, SHIFT, 44}, {9, SHIFT, 45}, },
			{{-1, REDUCE, 7}, {5, SHIFT, 41}, {6, SHIFT, 42}, {7, SHIFT, 43}, {8, SHIFT, 44}, {9, SHIFT, 45}, },
			{{-1, REDUCE, 10}, {0, SHIFT, 46}, {1, SHIFT, 47}, },
			{{-1, REDUCE, 11}, {0, SHIFT, 46}, {1, SHIFT, 47}, },
			{{-1, REDUCE, 12}, {0, SHIFT, 46}, {1, SHIFT, 47}, },
			{{-1, REDUCE, 13}, {0, SHIFT, 46}, {1, SHIFT, 47}, },
			{{-1, REDUCE, 14}, {0, SHIFT, 46}, {1, SHIFT, 47}, },
			{{-1, REDUCE, 16}, {2, SHIFT, 48}, {3, SHIFT, 49}, {4, SHIFT, 50}, },
			{{-1, REDUCE, 17}, {2, SHIFT, 48}, {3, SHIFT, 49}, {4, SHIFT, 50}, },
			{{-1, REDUCE, 19}, {10, SHIFT, 1}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, REDUCE, 20}, {10, SHIFT, 1}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, REDUCE, 21}, {10, SHIFT, 1}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 71}, {17, SHIFT, 76}, },
			{{-1, REDUCE, 4}, },
			{{-1, ERROR, 73}, {10, SHIFT, 1}, {15, SHIFT, 2}, {18, SHIFT, 3}, {19, SHIFT, 4}, {21, SHIFT, 5}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 74}, {20, SHIFT, 78}, },
			{{-1, REDUCE, 5}, },
			{{-1, ERROR, 76}, {10, SHIFT, 1}, {15, SHIFT, 2}, {18, SHIFT, 3}, {19, SHIFT, 4}, {21, SHIFT, 5}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, ERROR, 77}, {20, SHIFT, 80}, },
			{{-1, ERROR, 78}, {10, SHIFT, 1}, {15, SHIFT, 2}, {18, SHIFT, 3}, {19, SHIFT, 4}, {21, SHIFT, 5}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, REDUCE, 1}, },
			{{-1, ERROR, 80}, {10, SHIFT, 1}, {15, SHIFT, 2}, {18, SHIFT, 3}, {19, SHIFT, 4}, {21, SHIFT, 5}, {22, SHIFT, 6}, {23, SHIFT, 7}, {24, SHIFT, 8}, {25, SHIFT, 9}, {26, SHIFT, 10}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 3}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 11}, {1, 32}, {54, 71}, {55, 72}, {57, 74}, {58, 75}, {73, 77}, {76, 79}, {78, 81}, {80, 82}, },
			{{-1, 12}, {2, 34}, },
			{{-1, 13}, {39, 59}, {40, 60}, },
			{{-1, 14}, {41, 61}, {42, 62}, {43, 63}, {44, 64}, {45, 65}, },
			{{-1, 15}, {46, 66}, {47, 67}, },
			{{-1, 16}, {48, 68}, {49, 69}, {50, 70}, },
			{{-1, 17}, {16, 51}, {68, 51}, {69, 51}, {70, 51}, },
			{{-1, 18}, },
			{{-1, 19}, },
			{{-1, 33}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: '(', 'if', 'lambda', 'let', 'rec', '()', 'true', 'false', number, identifier",
			"expecting: '+', '-', '*', '/', 'mod', '<', '>', '<=', '>=', '=', '(', '&&', '||', 'if', 'lambda', 'let', 'rec', '()', 'true', 'false', number, identifier",
			"expecting: '(', '()', 'true', 'false', number, identifier",
			"expecting: identifier",
			"expecting: 'rec', identifier",
			"expecting: '+', '-', '*', '/', 'mod', '<', '>', '<=', '>=', '=', '(', ')', '&&', '||', 'then', 'else', 'in', '()', 'true', 'false', number, identifier, EOF",
			"expecting: EOF",
			"expecting: ')', '&&', '||', 'else', 'in', EOF",
			"expecting: '<', '>', '<=', '>=', '=', ')', '&&', '||', 'then', 'else', 'in', EOF",
			"expecting: '+', '-', '<', '>', '<=', '>=', '=', ')', '&&', '||', 'then', 'else', 'in', EOF",
			"expecting: '+', '-', '*', '/', 'mod', '<', '>', '<=', '>=', '=', ')', '&&', '||', 'then', 'else', 'in', EOF",
			"expecting: ')'",
			"expecting: '&&', '||', 'then'",
			"expecting: '.'",
			"expecting: '='",
			"expecting: 'else'",
			"expecting: ')', 'else', 'in', EOF",
			"expecting: 'in'",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 4, 3, 5, 5, 5, 5, 5, 6, 7, 8, 9, 10, 5, 5, 5, 5, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 13, 3, 14, 13, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5, 0, 0, 14, 0, 0, 8, 8, 9, 9, 9, 9, 9, 10, 10, 5, 5, 5, 15, 16, 0, 17, 16, 0, 17, 0, 16, 0, 16, 16, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            actionTable = new int[length][][];
            for(int i = 0; i < actionTable.length; i++)
            {
                length = s.readInt();
                actionTable[i] = new int[length][3];
                for(int j = 0; j < actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
