/* This file was generated by SableCC (http://www.sablecc.org/). */

package l1.parser;

import l1.node.*;
import l1.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTPlus(TPlus node)
    {
        index = 0;
    }

    public void caseTMinus(TMinus node)
    {
        index = 1;
    }

    public void caseTMultiply(TMultiply node)
    {
        index = 2;
    }

    public void caseTDivide(TDivide node)
    {
        index = 3;
    }

    public void caseTModulo(TModulo node)
    {
        index = 4;
    }

    public void caseTLowerThan(TLowerThan node)
    {
        index = 5;
    }

    public void caseTGreaterThan(TGreaterThan node)
    {
        index = 6;
    }

    public void caseTLowerEqual(TLowerEqual node)
    {
        index = 7;
    }

    public void caseTGreaterEqual(TGreaterEqual node)
    {
        index = 8;
    }

    public void caseTEqual(TEqual node)
    {
        index = 9;
    }

    public void caseTLeftParen(TLeftParen node)
    {
        index = 10;
    }

    public void caseTRightParen(TRightParen node)
    {
        index = 11;
    }

    public void caseTDot(TDot node)
    {
        index = 12;
    }

    public void caseTIf(TIf node)
    {
        index = 13;
    }

    public void caseTThen(TThen node)
    {
        index = 14;
    }

    public void caseTElse(TElse node)
    {
        index = 15;
    }

    public void caseTLambda(TLambda node)
    {
        index = 16;
    }

    public void caseTLet(TLet node)
    {
        index = 17;
    }

    public void caseTIn(TIn node)
    {
        index = 18;
    }

    public void caseTRec(TRec node)
    {
        index = 19;
    }

    public void caseTUnit(TUnit node)
    {
        index = 20;
    }

    public void caseTTrue(TTrue node)
    {
        index = 21;
    }

    public void caseTFalse(TFalse node)
    {
        index = 22;
    }

    public void caseTNumber(TNumber node)
    {
        index = 23;
    }

    public void caseTIdentifier(TIdentifier node)
    {
        index = 24;
    }

    public void caseEOF(EOF node)
    {
        index = 25;
    }
}
