package ui.core;

/**
 * TODO Add documentation here
 *
 * @author Benedikt Meurer
 * @version $Id$
 */
public class FilePane extends javax.swing.JPanel {
  /**
   * Allocates a new <code>FilePane</code> instance.
   */
  public FilePane() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    fileToolBar = new javax.swing.JToolBar();
    sourceButton = new javax.swing.JButton();

    setLayout(new java.awt.BorderLayout());

    fileToolBar.setFloatable(false);
    sourceButton.setBackground(javax.swing.UIManager.getDefaults().getColor("TabbedPane.selected"));
    sourceButton.setText("Source");
    sourceButton.setFocusable(false);
    fileToolBar.add(sourceButton);

    add(fileToolBar, java.awt.BorderLayout.NORTH);

  }// </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JToolBar fileToolBar;
  private javax.swing.JButton sourceButton;
  // End of variables declaration//GEN-END:variables
}
