package ui.core;

import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * TODO Add documentation here.
 *
 * @author Benedikt Meurer
 * @version $Id$
 */
public class MainWindow extends JFrame {
  //
  // Constructor
  //
  
  /**
   * Allocates a new <code>MainWindow</code> instance.
   */
  public MainWindow() {
    initComponents();
  }

  
  
  //
  // Component initialization
  //
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    javax.swing.JSeparator jSeparator1;
    javax.swing.JMenuItem newMenuItem;
    javax.swing.JButton newToolButton;
    javax.swing.JMenuItem openMenuItem;
    javax.swing.JButton openToolButton;
    javax.swing.JMenuItem quitMenuItem;

    mainToolBar = new javax.swing.JToolBar();
    newToolButton = new javax.swing.JButton();
    openToolButton = new javax.swing.JButton();
    tabbedPane = new javax.swing.JTabbedPane();
    mainMenu = new javax.swing.JMenuBar();
    fileMenu = new javax.swing.JMenu();
    newMenuItem = new javax.swing.JMenuItem();
    openMenuItem = new javax.swing.JMenuItem();
    jSeparator1 = new javax.swing.JSeparator();
    quitMenuItem = new javax.swing.JMenuItem();
    editMenu = new javax.swing.JMenu();
    undoMenuItem = new javax.swing.JMenuItem();
    redoMenuItem = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle("TPML 0.2.0");
    setName("mainWindow");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    mainToolBar.setFloatable(false);
    mainToolBar.setRollover(true);
    newToolButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/core/icons/new24.gif")));
    newToolButton.setToolTipText("New File...");
    newToolButton.setBorderPainted(false);
    newToolButton.setFocusable(false);
    newToolButton.setOpaque(false);
    newToolButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        newMenuItemActionPerformed(evt);
      }
    });

    mainToolBar.add(newToolButton);

    openToolButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/core/icons/open24.gif")));
    openToolButton.setToolTipText("Open File...");
    openToolButton.setBorderPainted(false);
    openToolButton.setFocusable(false);
    openToolButton.setOpaque(false);
    mainToolBar.add(openToolButton);

    getContentPane().add(mainToolBar, java.awt.BorderLayout.NORTH);

    getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

    fileMenu.setMnemonic('F');
    fileMenu.setText("File");
    newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
    newMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/core/icons/new16.gif")));
    newMenuItem.setMnemonic('N');
    newMenuItem.setText("New File...");
    newMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        newMenuItemActionPerformed(evt);
      }
    });

    fileMenu.add(newMenuItem);

    openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
    openMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/core/icons/open16.gif")));
    openMenuItem.setMnemonic('O');
    openMenuItem.setText("Open File...");
    fileMenu.add(openMenuItem);

    fileMenu.add(jSeparator1);

    quitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
    quitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/core/icons/empty16.gif")));
    quitMenuItem.setMnemonic('Q');
    quitMenuItem.setText("Quit");
    quitMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        quitMenuItemActionPerformed(evt);
      }
    });

    fileMenu.add(quitMenuItem);

    mainMenu.add(fileMenu);

    editMenu.setMnemonic('E');
    editMenu.setText("Edit");
    undoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
    undoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/core/icons/undo16.gif")));
    undoMenuItem.setMnemonic('U');
    undoMenuItem.setText("Undo");
    editMenu.add(undoMenuItem);

    redoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
    redoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/core/icons/redo16.gif")));
    redoMenuItem.setMnemonic('R');
    redoMenuItem.setText("Redo");
    editMenu.add(redoMenuItem);

    mainMenu.add(editMenu);

    setJMenuBar(mainMenu);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed
    FileWizard wizard = new FileWizard(this, true);
    wizard.setLocationRelativeTo(this);
    wizard.setVisible(true);
  }//GEN-LAST:event_newMenuItemActionPerformed

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    System.exit(0);
  }//GEN-LAST:event_formWindowClosing

  private void quitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitMenuItemActionPerformed
    // fake a WindowEvent telling the window that we want to close it
    processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
  }//GEN-LAST:event_quitMenuItemActionPerformed
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        MainWindow mainWindow = new MainWindow();
        mainWindow.setSize(680, 490);
        mainWindow.setVisible(true);
      }
    });
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenu editMenu;
  private javax.swing.JMenu fileMenu;
  private javax.swing.JMenuBar mainMenu;
  private javax.swing.JToolBar mainToolBar;
  private javax.swing.JMenuItem redoMenuItem;
  private javax.swing.JTabbedPane tabbedPane;
  private javax.swing.JMenuItem undoMenuItem;
  // End of variables declaration//GEN-END:variables
}
