package de.unisiegen.tpml.core.languages;


/**
 * Abstract base class for classes that implement the
 * {@link de.unisiegen.tpml.core.languages.LanguageTypeScanner} interface.
 * 
 * @author Benedikt Meurer
 * @version $Rev:380 $
 * @see de.unisiegen.tpml.core.languages.AbstractLanguageScanner
 * @see de.unisiegen.tpml.core.languages.LanguageTypeScanner
 */
public abstract class AbstractLanguageTypeScanner extends
    AbstractLanguageScanner implements LanguageTypeScanner
{

  //
  // Constructor (protected)
  //

  /**
   * Allocates a new <code>AbstractLanguageScanner</code>, which implements
   * the <code>LanguageScanner</code> interface and should be used as base
   * class for all scanners generated by JFlex.
   */
  protected AbstractLanguageTypeScanner ()
  {
    super ();
  }
}
