package de.unisiegen.tpml.core.languages;


/**
 * Abstract base class for classes that implement the
 * {@link LanguageUnifyScanner} interface.
 * 
 * @author Christian Fehler
 * @version $Id$
 */
public abstract class AbstractLanguageUnifyScanner extends
    AbstractLanguageScanner implements LanguageUnifyScanner
{

  /**
   * Allocates a new <code>AbstractLanguageUnifyScanner</code>, which
   * implements the <code>LanguageScanner</code> interface and should be used
   * as base class for all scanners generated by JFlex.
   */
  protected AbstractLanguageUnifyScanner ()
  {
    super ();
  }
}
