/* This file was generated by SableCC (http://www.sablecc.org/). */

package l1.node;

import java.util.*;
import l1.analysis.*;

public final class AInfixExpression extends PExpression
{
    private PExpression _e1_;
    private PExpression _op_;
    private PExpression _e2_;

    public AInfixExpression()
    {
    }

    public AInfixExpression(
        PExpression _e1_,
        PExpression _op_,
        PExpression _e2_)
    {
        setE1(_e1_);

        setOp(_op_);

        setE2(_e2_);

    }
    public Object clone()
    {
        return new AInfixExpression(
            (PExpression) cloneNode(_e1_),
            (PExpression) cloneNode(_op_),
            (PExpression) cloneNode(_e2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInfixExpression(this);
    }

    public PExpression getE1()
    {
        return _e1_;
    }

    public void setE1(PExpression node)
    {
        if(_e1_ != null)
        {
            _e1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _e1_ = node;
    }

    public PExpression getOp()
    {
        return _op_;
    }

    public void setOp(PExpression node)
    {
        if(_op_ != null)
        {
            _op_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _op_ = node;
    }

    public PExpression getE2()
    {
        return _e2_;
    }

    public void setE2(PExpression node)
    {
        if(_e2_ != null)
        {
            _e2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _e2_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_e1_)
            + toString(_op_)
            + toString(_e2_);
    }

    void removeChild(Node child)
    {
        if(_e1_ == child)
        {
            _e1_ = null;
            return;
        }

        if(_op_ == child)
        {
            _op_ = null;
            return;
        }

        if(_e2_ == child)
        {
            _e2_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_e1_ == oldChild)
        {
            setE1((PExpression) newChild);
            return;
        }

        if(_op_ == oldChild)
        {
            setOp((PExpression) newChild);
            return;
        }

        if(_e2_ == oldChild)
        {
            setE2((PExpression) newChild);
            return;
        }

    }
}
