/* This file was generated by SableCC (http://www.sablecc.org/). */

package l1.node;

import java.util.*;
import l1.analysis.*;

public final class ALetrecExpression extends PExpression
{
    private TIdentifier _id_;
    private PExpression _e1_;
    private PExpression _e2_;

    public ALetrecExpression()
    {
    }

    public ALetrecExpression(
        TIdentifier _id_,
        PExpression _e1_,
        PExpression _e2_)
    {
        setId(_id_);

        setE1(_e1_);

        setE2(_e2_);

    }
    public Object clone()
    {
        return new ALetrecExpression(
            (TIdentifier) cloneNode(_id_),
            (PExpression) cloneNode(_e1_),
            (PExpression) cloneNode(_e2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALetrecExpression(this);
    }

    public TIdentifier getId()
    {
        return _id_;
    }

    public void setId(TIdentifier node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public PExpression getE1()
    {
        return _e1_;
    }

    public void setE1(PExpression node)
    {
        if(_e1_ != null)
        {
            _e1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _e1_ = node;
    }

    public PExpression getE2()
    {
        return _e2_;
    }

    public void setE2(PExpression node)
    {
        if(_e2_ != null)
        {
            _e2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _e2_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_e1_)
            + toString(_e2_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_e1_ == child)
        {
            _e1_ = null;
            return;
        }

        if(_e2_ == child)
        {
            _e2_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((TIdentifier) newChild);
            return;
        }

        if(_e1_ == oldChild)
        {
            setE1((PExpression) newChild);
            return;
        }

        if(_e2_ == oldChild)
        {
            setE2((PExpression) newChild);
            return;
        }

    }
}
