/* This file was generated by SableCC (http://www.sablecc.org/). */

package l1.node;

import java.util.*;
import l1.analysis.*;

public final class AModuloExpression extends PExpression
{
    private TModulo _modulo_;

    public AModuloExpression()
    {
    }

    public AModuloExpression(
        TModulo _modulo_)
    {
        setModulo(_modulo_);

    }
    public Object clone()
    {
        return new AModuloExpression(
            (TModulo) cloneNode(_modulo_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModuloExpression(this);
    }

    public TModulo getModulo()
    {
        return _modulo_;
    }

    public void setModulo(TModulo node)
    {
        if(_modulo_ != null)
        {
            _modulo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _modulo_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_modulo_);
    }

    void removeChild(Node child)
    {
        if(_modulo_ == child)
        {
            _modulo_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_modulo_ == oldChild)
        {
            setModulo((TModulo) newChild);
            return;
        }

    }
}
