/* This file was generated by SableCC (http://www.sablecc.org/). */

package l1.node;

import l1.analysis.*;

public final class TGreaterThan extends Token
{
    public TGreaterThan()
    {
        super.setText(">");
    }

    public TGreaterThan(int line, int pos)
    {
        super.setText(">");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TGreaterThan(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGreaterThan(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TGreaterThan text.");
    }
}
