/* This file was generated by SableCC (http://www.sablecc.org/). */

package l1.node;

import l1.analysis.*;

public final class TLambda extends Token
{
    public TLambda()
    {
        super.setText("lambda");
    }

    public TLambda(int line, int pos)
    {
        super.setText("lambda");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLambda(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLambda(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLambda text.");
    }
}
