/* This file was generated by SableCC (http://www.sablecc.org/). */

package l1.node;

import l1.analysis.*;

public final class TLowerThan extends Token
{
    public TLowerThan()
    {
        super.setText("<");
    }

    public TLowerThan(int line, int pos)
    {
        super.setText("<");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLowerThan(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLowerThan(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLowerThan text.");
    }
}
