/* This file was generated by SableCC (http://www.sablecc.org/). */

package l1.node;

import l1.analysis.*;

public final class TMultiply extends Token
{
    public TMultiply()
    {
        super.setText("*");
    }

    public TMultiply(int line, int pos)
    {
        super.setText("*");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMultiply(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMultiply(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMultiply text.");
    }
}
