/* This file was generated by SableCC (http://www.sablecc.org/). */

package l1.node;

import l1.analysis.*;

public final class TThen extends Token
{
    public TThen()
    {
        super.setText("then");
    }

    public TThen(int line, int pos)
    {
        super.setText("then");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TThen(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTThen(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TThen text.");
    }
}
