/* This file was generated by SableCC (http://www.sablecc.org/). */

package l1.node;

import l1.analysis.*;

public final class TUnit extends Token
{
    public TUnit()
    {
        super.setText("()");
    }

    public TUnit(int line, int pos)
    {
        super.setText("()");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TUnit(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUnit(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TUnit text.");
    }
}
